# 正向傳導程式撰寫

In [7]:
input = np.array([3,5]).reshape(1,2)
w1 = np.array([2,4,4,-5]).reshape(2,2)
layer1 = input @ w1
layer1

array([[ 26, -13]])

In [8]:
w2 = np.array([-1,2,1,2]).reshape(2,2)
layer2 = layer1 @ w2
layer2

array([[-39,  26]])

In [9]:
w3 = np.array([-3,7]).reshape(2,1)
output = layer2 @ w3
output

array([[299]])