# 特徵向量(eigenvector)及特徵值(eigenvalue)

## 載入套件

In [70]:
import numpy as np

## 建立測試資料

In [71]:
A = np.array([[2,0],
              [0,3]])

## 求矩陣A的 eigenvalue and eigenvector

In [72]:
eVals, eVecs = np.linalg.eig(A)
print('特徵值(eigenvalue):\n', eVals)
print('特徵向量(eigenvector):\n', eVecs)

特徵值(eigenvalue):
 [2. 3.]
特徵向量(eigenvector):
 [[1. 0.]
 [0. 1.]]


## 驗算：參閱[『拾人牙慧，特徵向量(Eigenvector) 及 特徵值(Eigenvalue) 的定義及求法』](https://silverwind1982.pixnet.net/blog/post/154593170)

$ A\vec{v} = \lambda\vec{v}$

## 驗算
### 兩對 $\lambda$：
$ \lambda_{1} = 2, \vec{v_{1}} = \begin{bmatrix}1 \\ 0\end{bmatrix}  \;\;\;\;\;\; \lambda_{2} = 3, \vec{v_{2}} = \begin{bmatrix}0 \\ 1\end{bmatrix} $

$ 2 \times \begin{bmatrix}1 \\ 0\end{bmatrix} = \begin{bmatrix}2 \\ 0\end{bmatrix}  \;\;\;and\;\;\; \begin{bmatrix}2 & 0\\0 & 3\end{bmatrix} \cdot \begin{bmatrix}1 \\ 0\end{bmatrix} = \begin{bmatrix}2 \\ 0\end{bmatrix} $


In [73]:
# 只比對斜對角
np.allclose(np.diagonal(A @ eVecs), np.diagonal(np.diag(eVals) @ eVecs))

True

## 另一測試資料

In [74]:
A = np.array([[1,2],
              [3,2]])
eVals, eVecs = np.linalg.eig(A)
print('特徵值(eigenvalue):\n', eVals)
print('特徵向量(eigenvector):\n', eVecs)

特徵值(eigenvalue):
 [-1.  4.]
特徵向量(eigenvector):
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [75]:
# 只比對斜對角
np.allclose(np.diagonal(A @ eVecs), np.diagonal(np.diag(eVals) @ eVecs))

True

In [76]:
A @ eVecs

array([[ 0.70710678, -2.21880078],
       [-0.70710678, -3.32820118]])

In [77]:
np.diag(eVals) @ eVecs

array([[ 0.70710678,  0.5547002 ],
       [ 2.82842712, -3.32820118]])