# 以Scikit-learn SVM進行鳶尾花(Iris)品種的辨識

## 載入相關套件

In [11]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

## 載入資料集

In [12]:
X, y = datasets.load_iris(return_X_y=True)

## 資料分割

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

## 特徵縮放

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

## 模型訓練

In [15]:
from sklearn.svm import SVC

clf = SVC(probability=True)
clf.fit(X_train_std, y_train)

SVC(probability=True)

## 模型評分

In [16]:
# 計算準確率
y_pred = clf.predict(X_test_std)
print(f'{accuracy_score(y_test, y_pred)*100:.2f}%') 

90.00%


In [17]:
clf.support_vectors_

array([[-1.72355547, -0.36604246, -1.37008031, -1.34489172],
       [-0.90559694,  0.57858324, -1.20087656, -0.94965824],
       [-0.08763841,  2.2316782 , -1.4828828 , -1.34489172],
       [-1.60670425, -1.782981  , -1.42648155, -1.21314723],
       [-1.72355547,  0.34242681, -1.42648155, -1.34489172],
       [-1.84040669, -0.12988603, -1.53928405, -1.47663622],
       [-0.55504329,  0.81473966, -1.31367906, -1.08140273],
       [-1.48985303,  1.28705251, -1.5956853 , -1.34489172],
       [-1.02244816, -0.12988603, -1.25727781, -1.34489172],
       [-0.43819207,  2.70399105, -1.37008031, -1.34489172],
       [ 0.96402255,  0.10627039,  0.49116086,  0.36778672],
       [ 0.96402255, -0.12988603,  0.66036461,  0.63127571],
       [ 0.14606402, -0.36604246,  0.37835837,  0.36778672],
       [ 0.0292128 ,  0.34242681,  0.54756211,  0.7630202 ],
       [ 0.14606402,  0.81473966,  0.37835837,  0.49953121],
       [ 0.49661768,  0.57858324,  0.49116086,  0.49953121],
       [-1.02244816, -2.

In [18]:
clf.support_

array([ 28,  35,  37,  41,  48,  54,  58,  81,  85,  86,   2,   8,  10,
        11,  20,  31,  34,  47,  63,  69,  70,  73,  79,  84,  88,  89,
        93, 100, 116,  13,  16,  18,  21,  25,  30,  32,  42,  50,  65,
        78,  92, 102, 104, 105, 117, 118])

In [19]:
clf.predict_proba(X_test)

array([[0.27989109, 0.35563274, 0.36447617],
       [0.29615597, 0.3719181 , 0.33192593],
       [0.23403051, 0.30171653, 0.46425296],
       [0.29343777, 0.36920086, 0.33736138],
       [0.27946987, 0.35509016, 0.36543997],
       [0.29353398, 0.36927159, 0.33719443],
       [0.29605237, 0.37181682, 0.33213082],
       [0.29616257, 0.371927  , 0.33191043],
       [0.28563422, 0.35936028, 0.3550055 ],
       [0.29640379, 0.37216684, 0.33142938],
       [0.26880423, 0.34477033, 0.38642543],
       [0.2963905 , 0.37215338, 0.33145612],
       [0.29613784, 0.37190154, 0.33196062],
       [0.2913541 , 0.36703712, 0.34160878],
       [0.29154991, 0.36726194, 0.34118816],
       [0.27372952, 0.34854847, 0.37772201],
       [0.2862849 , 0.36152227, 0.35219283],
       [0.28860671, 0.36847114, 0.34292215],
       [0.29595   , 0.37171086, 0.33233913],
       [0.29638644, 0.37214921, 0.33146435],
       [0.2950402 , 0.37079505, 0.33416475],
       [0.29644062, 0.37220356, 0.33135582],
       [0.

In [20]:
clf.predict_log_proba(X_test)

array([[-1.2733547 , -1.03385671, -1.00929412],
       [-1.21686902, -0.98908162, -1.10284344],
       [-1.45230378, -1.19826735, -0.7673257 ],
       [-1.2260897 , -0.99641446, -1.08660058],
       [-1.27486078, -1.03538356, -1.00665325],
       [-1.22576187, -0.99622288, -1.08709558],
       [-1.21721893, -0.98935397, -1.10222636],
       [-1.21684675, -0.98905768, -1.10289013],
       [-1.25304324, -1.02342983, -1.035622  ],
       [-1.21603261, -0.98841304, -1.10434053],
       [-1.31377192, -1.06487678, -0.95081636],
       [-1.21607743, -0.98844919, -1.10425986],
       [-1.21693027, -0.98912613, -1.10273893],
       [-1.23321591, -1.00229229, -1.07408912],
       [-1.23254408, -1.00167996, -1.07532117],
       [-1.29561482, -1.05397797, -0.97359678],
       [-1.25076783, -1.01743163, -1.04357643],
       [-1.2426904 , -0.99839288, -1.07025182],
       [-1.21756475, -0.98963898, -1.10159934],
       [-1.21609114, -0.98846039, -1.10423503],
       [-1.22064366, -0.99210579, -1.096